# Set this to false if you don't want the robot to check for new versions released on GitHub
check_for_new_versions: true

# This is the path to the sqlite3 database this app will use to store some data.
# The DB  will be created if it doesn't exist i.e. on first-run.
db_path: data.db

# This section is all about where the notifications end up
output:
  # Do you want to see notifications in the console?
  console: true

# Check your RSS feeds
rss:
  # How often to check the feeds?
  check:
    frequency: half_hourly
  # A list of important keywords to look for. These will be highlighted in the notifications
  important_keywords:
    - npm
    - npmjs
    - package
    - malware
    - pypi
  feeds:
    - group:
      html:
        tag: body
        important_keywords:
          - npm
          - npmjs
          - package
          - malware
          - pypi
      feeds:
      - name: Socket
        url: https://socket.dev/api/blog/feed.atom
      - name: TheHackersNews
        url: https://feeds.feedburner.com/TheHackersNews
      - name: Ars Technica
        url: https://feeds.arstechnica.com/arstechnica/index
    - group:
      html:
        tag: article
        important_keywords:
          - npm
          - npmjs
          - package
          - malware
          - pypi
      feeds:
        - name: BleepingComputer
          url: https://www.bleepingcomputer.com/feed/
